### ISSUE TITLE
Iced Wars Victory Monument is not well setted

### ISSUE THREAD

**Issue by guillevn** [MrTheSharpie/XML#1]
Doom made the XML,Twizmwazin fixed it, and it most works but there is a big problem, the blocks to place the wools are a few blocks separated from the coords put on the XML. Could someone help me? :dancer:

**Comment by DoomRobotBoy** [comment]
Just put the coords of the victory monument in the place where the wrong ones are.

You can find these coordinates by clicking f3 (fn + f3 on Mac) and then you should copy the X, Y, Z coordinates; it should look something like this: `17.5,8,123.5`

**Comment by guillevn** [comment]
Ok, thank you, I will do it!

**Comment by guillevn** [comment]
@DoomRobotBoy Aparently they are well setted on the XML but then on the game it doesn't work :/

**Comment by RubeGamerV** [comment]
Issues linked, the problem is from the xml. #4
