### ISSUE TITLE
Electron XML has to full be re-done

### ISSUE THREAD

**Issue by guillevn** [MrTheSharpie/XML#4]
As I don't have any XML knowledge, what I've done is to change coordinates and that things on Fractal Descent XML. And the problem here is that I need a XML in the latest proto. If someone could do this, I'd be very grateful.

**Comment by ghost** [comment]
Que problema tienes exactamente?

**Comment by guillevn** [comment]
El xml está en el proto 1.3.2 y para overcast es obligatorio estar en el 1.3.6...

**Comment by ghost** [comment]
Pues yo miro los protocolos en la 1.3.2, mira https://maps.oc.tc/CTW/Standard/Battle%20Ecliptica%20II/map.xml

**Comment by ghost** [comment]
Añademe a la whitelist del server donde estas testeando el mapa. La ip ya la tengo

**Comment by guillevn** [comment]
Te paso la que uso para construir ok? para coordenadas y eso vale igual; porque en mi server hay un tio haciendo una defensa 37.59.12.45:25823

**Comment by vYuri** [comment]
Yo podría ayudarte, Se sobre xml (no mucho)

**Comment by guillevn** [comment]
Te añado como contributor :)

**Comment by vYuri** [comment]
Ok, gracias.

**Comment by guillevn** [comment]
Yo haré esto, he aprendido bastante de XML.

**Comment by guillevn** [comment]
#graciaseudald
