### ISSUE TITLE
The Towers [ALL] <Kits>

### ISSUE THREAD

**Issue by vYuri** [MrTheSharpie/XML#6]
Los kits de The Towers no son los originales, no será mejor dejar el juego original? la jugabilidad.

**Comment by ghost** [comment]
Es mejor sin kits

**Comment by vYuri** [comment]
Entonces, si es mejor sin kits, para que añadiste los kits? No entiendo

**Comment by ghost** [comment]
Yo no añadie los kits a ningun mapa de the towers

**Comment by vYuri** [comment]
f09cc2b

**Comment by ghost** [comment]
Ya miraste el mapa?

**Comment by ghost** [comment]
Ese xml es para este mapa https://oc.tc/forums/topics/55190e9d5f35b9309c00e460 no para el the towers. "Two Towers"

**Comment by vYuri** [comment]
Tengo retraso.

**Comment by ghost** [comment]
Np xD
