### ISSUE TITLE
Kits doesn't load on your inventory - The Wall

### ISSUE THREAD

**Issue by guillevn** [MrTheSharpie/XML#7]

**Comment by vYuri** [comment]
Esto sucede con todos los kits o alguno en especial?

**Comment by guillevn** [comment]
Con todos. Según me han dicho es que CardinalPGM a veces carga mal los kits.

**Comment by ghost** [comment]
Entonces si es problema del cardinal hay que reportarlo aya, pero primero hay que confirmar

**Comment by guillevn** [comment]
Lo he reportado allí ya, estoy esperando respuesta

**Comment by ghost** [comment]
dale

**Comment by guillevn** [comment]
Fixed on #e988b37c
